{
  config,
  lib,
  pkgs,
  ...
}:

let
  outboxDir = "${config.home.homeDirectory}/dropbox-outbox";
  # No existing out-of-store secrets convention was found on nix-mac (no
  # /etc/nix-darwin/secrets precedent, no other launchd.agents usage to
  # confirm home-manager's darwin launchd support is already exercised
  # there). This path mirrors nix-server's /etc/nixos/secrets convention,
  # using nix-darwin's actual on-disk config directory (/etc/nix-darwin,
  # per aj-skhd.nix's reference to /private/etc/nix-darwin/flake.nix).
  secretsFile =
    if pkgs.stdenv.isDarwin then
      "/etc/nix-darwin/secrets/agent-dropbox.env"
    else
      "/etc/nixos/secrets/agent-dropbox.env";
  # Matches AWS_DEFAULT_REGION already in use on nix-server and the region
  # the aj-agent-dropbox bucket was actually created in.
  awsRegion = "us-east-1";
  syncArgs = [
    "move"
    outboxDir
    "dropbox:aj-agent-dropbox/"
    "--min-age"
    "30s"
  ];
in
lib.mkMerge [
  {
    home.packages = [ pkgs.rclone ];

    home.file."dropbox-outbox/.keep".text = "";

    # Writes/updates the [dropbox] S3 remote in ~/.config/rclone/rclone.conf.
    # Credentials come from a per-host secrets file, provisioned out-of-band
    # (never generated by Nix) — mirrors the ngrok.env pattern on nix-server.
    # A missing secrets file is silently skipped, not an error, so this
    # module is safe to import before the secret is provisioned on a host.
    home.activation.agentDropboxRcloneConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      if [ -r "${secretsFile}" ]; then
        set -a
        . "${secretsFile}"
        set +a
        run ${pkgs.rclone}/bin/rclone config create dropbox s3 \
          provider=AWS \
          access_key_id="$AGENT_DROPBOX_ACCESS_KEY_ID" \
          secret_access_key="$AGENT_DROPBOX_SECRET_ACCESS_KEY" \
          region=${awsRegion} \
          --non-interactive
      fi
    '';
  }
  (lib.mkIf pkgs.stdenv.isDarwin {
    launchd.agents.agent-dropbox-sync = {
      enable = true;
      config = {
        ProgramArguments = [ "${pkgs.rclone}/bin/rclone" ] ++ syncArgs;
        StartInterval = 300;
        RunAtLoad = false;
      };
    };
  })
  (lib.mkIf (!pkgs.stdenv.isDarwin) {
    systemd.user.services.agent-dropbox-sync = {
      Unit.Description = "Sync agent-dropbox outbox to S3";
      Service = {
        Type = "oneshot";
        ExecStart = "${pkgs.rclone}/bin/rclone ${lib.concatStringsSep " " syncArgs}";
      };
    };
    systemd.user.timers.agent-dropbox-sync = {
      Unit.Description = "Timer for agent-dropbox-sync";
      Timer = {
        OnBootSec = "5min";
        OnUnitActiveSec = "5min";
      };
      Install.WantedBy = [ "timers.target" ];
    };
  })
]
