# Restic backups to a shared Backblaze B2 bucket, one repository per host.
#
# This is a thin wrapper around home-manager's services.restic. Upstream owns
# the systemd service, the timer, repository initialization, forget/prune, and
# the restic-b2 restore wrapper. This module only encodes the shared B2
# convention and the secret file locations.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.resticBackup;
in
{
  options.services.resticBackup = {
    enable = lib.mkEnableOption "restic backups to the shared Backblaze B2 bucket";

    hostName = lib.mkOption {
      type = lib.types.str;
      default = "";
      example = "nix-server";
      description = ''
        Subdirectory of the shared bucket this host backs up into, giving it
        its own restic repository at `b2:<bucket>:<hostName>`. Hosts therefore
        never contend for one repository lock, at the cost of no deduplication
        between hosts.

        Set explicitly rather than derived from the runtime hostname: a host
        that renames itself would otherwise silently start a new repository
        and a fresh full backup.
      '';
    };

    bucket = lib.mkOption {
      type = lib.types.str;
      default = "";
      example = "aj-backups";
      description = ''
        Backblaze B2 bucket shared by every host. Not a secret, so it lives in
        Nix rather than in the environment file.
      '';
    };

    paths = lib.mkOption {
      type = with lib.types; listOf str;
      default = [ ];
      example = [ "/home/aj/documents" ];
      description = "Paths to back up.";
    };

    exclude = lib.mkOption {
      type = with lib.types; listOf str;
      default = [ ];
      example = [ "**/node_modules" ];
      description = ''
        Patterns to exclude. See
        <https://restic.readthedocs.io/en/stable/040_backup.html#excluding-files>.
      '';
    };

    timerConfig = lib.mkOption {
      type = lib.types.attrs;
      default = {
        OnCalendar = "daily";
        Persistent = true;
        RandomizedDelaySec = "1h";
      };
      description = ''
        Passed through to the systemd timer. `Persistent` makes a host that was
        powered off at the scheduled time run the backup after it next boots.
        `RandomizedDelaySec` keeps several hosts from hitting B2 at the same
        instant. See {manpage}`systemd.timer(5)`.
      '';
    };

    pruneOpts = lib.mkOption {
      type = with lib.types; listOf str;
      default = [
        "--keep-daily 7"
        "--keep-weekly 4"
        "--keep-monthly 6"
      ];
      description = ''
        Policy for `restic forget --prune`, which upstream runs in the same
        service invocation as the backup. Roughly 17 snapshots are retained.
      '';
    };

    environmentFile = lib.mkOption {
      # Deliberately str, not path: a path-typed option would copy this file
      # into the world-readable Nix store at evaluation time, and would fail to
      # evaluate on any machine where the file is absent.
      type = lib.types.str;
      default = "/etc/nixos/secrets/restic.env";
      description = ''
        File holding `B2_ACCOUNT_ID` and `B2_ACCOUNT_KEY`, in
        {manpage}`systemd.exec(5)` EnvironmentFile format. Provisioned out of
        band. Never generated by Nix, never committed.
      '';
    };

    passwordFile = lib.mkOption {
      # str, not path -- same reason as environmentFile above.
      type = lib.types.str;
      default = "/etc/nixos/secrets/restic-password";
      description = ''
        File holding the restic repository password. A separate file from
        `environmentFile` because upstream asserts that exactly one of
        `passwordFile` or `passwordCommand` is set, so the password cannot be
        supplied as an environment variable. Provisioned out of band.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = pkgs.stdenv.hostPlatform.isLinux;
        message = ''
          services.resticBackup supports Linux only. On other platforms
          home-manager's services.restic creates the restic-b2 wrapper script
          and nothing else -- no service, no timer -- pending launchd support
          (home-manager issue #7924). Enabling it on macOS would silently back
          nothing up.
        '';
      }
      {
        assertion = cfg.hostName != "";
        message = ''
          services.resticBackup.hostName must be set. It names this host's
          subdirectory in the shared B2 bucket.
        '';
      }
      {
        assertion = cfg.bucket != "";
        message = ''
          services.resticBackup.bucket must be set to the shared Backblaze B2
          bucket name.
        '';
      }
      {
        assertion = cfg.paths != [ ];
        message = ''
          services.resticBackup.paths must list at least one path to back up.
        '';
      }
    ];

    services.restic = {
      enable = true;

      # Named "b2" rather than after the host so the restore wrapper is always
      # `restic-b2`, and so hosts have a stable option path to reach through on
      # for upstream options this module does not re-export, for example
      # `services.restic.backups.b2.runCheck = true`.
      backups.b2 = {
        repository = "b2:${cfg.bucket}:${cfg.hostName}";
        initialize = true;
        inherit (cfg)
          paths
          exclude
          timerConfig
          pruneOpts
          environmentFile
          passwordFile
          ;
      };
    };
  };
}
