''
  ## ⚠️ Claude Config Files Are Generated — Edit the Nix Source

  Files under `~/.claude/` are generated by home-manager from the **nix-components** repo (`/var/lib/paseo/paseo-projects/nix-components`). **Never edit them directly** — changes will be silently overwritten on the next `home-manager switch`.

  | What you want to change | Edit this file in nix-components |
  |---|---|
  | `~/.claude/CLAUDE.md` / `~/.config/opencode/AGENTS.md` | `modules/lib/claude-md-content.nix` |
  | `~/.claude/skills/<name>/` | `skills/<name>/` |
  | Claude Code settings / MCP servers | `modules/claude-code.nix` |

  After editing, commit and push to trigger CI (`home-manager switch` via GitHub Actions).
''
