# Restic backups to the shared Backblaze B2 bucket, for nix-mac.
#
# modules/restic.nix (the home-manager wrapper around upstream
# services.restic.backups) is Linux only: home-manager's restic module marks
# most of its options read-only on non-Linux, pending launchd support
# (home-manager issue #7924), so it creates a restore wrapper and nothing
# else there. nix-darwin itself ships no restic module at all -- there is no
# upstream to wrap on this platform, unlike beszel-agent/tailscale/determinate,
# which all have a real darwin implementation to delegate to.
#
# This is therefore a from-scratch module: a plain root launchd daemon, same
# idiom as os-modules/beszel-agent/darwin.nix (root reads the secret files
# directly off disk -- there is no LoadCredential equivalent here). Restic
# itself is cross-platform and speaks B2 natively, so only the *scheduling*
# is hand-rolled; the backup/prune logic is a thin shell wrapper around the
# restic binary, not a reimplementation of it.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.nix-components.resticBackup;

  # Sourced by every restic-b2 invocation (scheduled or manual). `set -a` so
  # B2_ACCOUNT_ID/B2_ACCOUNT_KEY from environmentFile are exported without
  # needing `export` prefixes in that file.
  resticWrapper = pkgs.writeShellApplication {
    name = "restic-b2";
    runtimeInputs = [ pkgs.restic ];
    text = ''
      set -a
      # shellcheck disable=SC1091
      . ${lib.escapeShellArg cfg.environmentFile}
      set +a
      export RESTIC_REPOSITORY=${lib.escapeShellArg "b2:${cfg.bucket}:${cfg.hostName}"}
      export RESTIC_PASSWORD_FILE=${lib.escapeShellArg cfg.passwordFile}
      exec restic "$@"
    '';
  };

  backupScript = pkgs.writeShellApplication {
    name = "restic-backup-b2";
    runtimeInputs = [ resticWrapper ];
    text = ''
      restic-b2 snapshots >/dev/null 2>&1 || restic-b2 init
      restic-b2 backup ${lib.concatMapStringsSep " " lib.escapeShellArg cfg.paths} \
        ${lib.concatMapStringsSep " " (e: "--exclude " + lib.escapeShellArg e) cfg.exclude}
      restic-b2 forget --prune ${lib.concatStringsSep " " cfg.pruneOpts}
    '';
  };
in
{
  key = "nix-components-restic-backup-darwin";

  options.nix-components.resticBackup = {
    enable = lib.mkEnableOption "restic backups to the shared Backblaze B2 bucket";

    hostName = lib.mkOption {
      type = lib.types.str;
      default = "";
      example = "nix-mac";
      description = ''
        Subdirectory of the shared bucket this host backs up into, giving it
        its own restic repository at `b2:<bucket>:<hostName>`. Set explicitly
        rather than derived from the runtime hostname, so a renamed host does
        not silently start a fresh repository. Mirrors
        `services.resticBackup.hostName` in `modules/restic.nix`.
      '';
    };

    bucket = lib.mkOption {
      type = lib.types.str;
      default = "";
      example = "aj-backups";
      description = ''
        Backblaze B2 bucket shared by every host. Not a secret, so it lives in
        Nix rather than in the environment file.
      '';
    };

    paths = lib.mkOption {
      type = with lib.types; listOf str;
      default = [ ];
      example = [ "/Users/aj/Documents" ];
      description = "Paths to back up.";
    };

    exclude = lib.mkOption {
      type = with lib.types; listOf str;
      default = [ ];
      example = [ "**/node_modules" ];
      description = ''
        Patterns to exclude. See
        <https://restic.readthedocs.io/en/stable/040_backup.html#excluding-files>.
      '';
    };

    pruneOpts = lib.mkOption {
      type = with lib.types; listOf str;
      default = [
        "--keep-daily 7"
        "--keep-weekly 4"
        "--keep-monthly 6"
      ];
      description = ''
        Policy for `restic forget --prune`, run in the same launchd invocation
        as the backup. Roughly 17 snapshots are retained.
      '';
    };

    environmentFile = lib.mkOption {
      # Deliberately str, not path -- a path-typed option would copy this file
      # into the world-readable Nix store at evaluation time, and would fail
      # to evaluate on any machine where the file is absent.
      type = lib.types.str;
      default = "/etc/nix-darwin/secrets/restic.env";
      description = ''
        File holding `B2_ACCOUNT_ID` and `B2_ACCOUNT_KEY`, as plain
        `KEY=value` lines. Provisioned out of band. Never generated by Nix,
        never committed.
      '';
    };

    passwordFile = lib.mkOption {
      # str, not path -- same reason as environmentFile above.
      type = lib.types.str;
      default = "/etc/nix-darwin/secrets/restic-password";
      description = ''
        File holding the restic repository password, alone on one line.
        Provisioned out of band.
      '';
    };

    calendar = lib.mkOption {
      type = lib.types.attrs;
      default = {
        Hour = 3;
        Minute = 0;
      };
      description = ''
        Passed to launchd's `StartCalendarInterval`. Unlike systemd's
        `Persistent`, launchd has no catch-up for a missed run -- a Mac
        asleep at the scheduled time simply misses that day's backup rather
        than running it late. Acceptable for a single laptop.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.hostName != "";
        message = "nix-components.resticBackup.hostName must be set. It names this host's subdirectory in the shared B2 bucket.";
      }
      {
        assertion = cfg.bucket != "";
        message = "nix-components.resticBackup.bucket must be set to the shared Backblaze B2 bucket name.";
      }
      {
        assertion = cfg.paths != [ ];
        message = "nix-components.resticBackup.paths must list at least one path to back up.";
      }
    ];

    # restic-b2 on PATH for manual restores/inspection, matching the restore
    # wrapper home-manager's services.restic creates on Linux (see
    # modules/restic.nix).
    environment.systemPackages = [ resticWrapper ];

    launchd.daemons.restic-backup-b2 = {
      command = lib.getExe backupScript;
      serviceConfig = {
        StartCalendarInterval = [ cfg.calendar ];
        RunAtLoad = false;
        StandardOutPath = "/var/log/restic-backup-b2.log";
        StandardErrorPath = "/var/log/restic-backup-b2.log";
      };
    };
  };
}
